image: hosttoday/ht-docker-dbase:npmts
services:
  - docker:dind

stages:
- test
- release
- trigger

test:
  stage: test
  script:
    - npm install
    - npm test
  tags:
    - docker
    - lossless
    - priv

release:
  stage: release
  environment: npmjs-com_registry
  script:
    - npmci publish
  only:
    - tags
  tags:
    - docker
    - lossless
    - priv

trigger:
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
  tags:
    - docker
    - lossless
    - priv
