image: hosttoday/ht-docker-dbase:npmci
services:
  - docker:dind

stages:
- test
- release
- trigger
- pages

test:
  stage: test
  script:
    - npmci test stable
  tags:
    - docker
    - lossless
    - priv

release:
  stage: release
  environment: npmjs-com_registry
  script:
    - npmci publish
  only:
    - tags
  tags:
    - docker
    - lossless
    - priv

trigger:
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
  tags:
    - docker
    - lossless
    - priv

pages:
  image: hosttoday/ht-docker-node:npmci
  stage: pages
  script:
    - npmci command yarn global add npmpage
    - npmci command npmpage
  only:
    - tags
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
    - public
