image: hosttoday/ht-docker-dbase:npmts

stages:
- test
- release

test:
  stage: test
  script:
    - npm test
  tags:
    - docker

release:
  stage: release
  environment: npmjs-com_registry
  script:
    - npmci publish
  only:
    - tags
  tags:
    - docker
