image: hosttoday/ht-docker-dbase:npmci
services:
  - docker:dind

stages:
- mirror
- test
- release
- trigger
- pages

mirror:
  image: hosttoday/ht-docker-node:npmci
  stage: mirror
  script:
    - npmci git mirror
  tags:
    - docker


test:
  stage: test
  script:
    - npmci node install stable
    - npmci npm install
    - npmci npm test
  tags:
    - docker
    - lossless
    - priv

release:
  stage: release
  environment: npmjs-com_registry
  script:
    - npmci npm prepare
    - npmci npm publish
  only:
    - tags
  tags:
    - docker
    - lossless
    - priv

trigger:
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
  tags:
    - docker
    - lossless
    - priv

pages:
  image: hosttoday/ht-docker-node:npmci
  stage: pages
  script:
    - npmci command npm install -g @gitzone/tsdoc
    - npmci command tsdoc
  only:
    - tags
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
    - public
